name: Publish Docker image
on:
  workflow_dispatch:
  push:
    branches: ['main', 'stable-*', 'dev-*']
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name: ['mastodon', 'mastodon-streaming']
        include:
          - image-name: 'mastodon'
            image-context: '.'
            cache: True
          - image-name: 'mastodon-streaming'
            image-context: 'streaming/'
            cache: False
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image-name }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ matrix.image-context }}/Dockerfile
          context: ${{ matrix.image-image-context }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: ${{ matrix.cache && 'type=gha' || '' }}
          cache-to: ${{ matrix.cache && 'type=gha,mode=max' || '' }}
